name: 'AppStore - copy Provisioning Profile'
description: 'Copy Provisioning Profile'
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to take the provisioning profile'
    default: '.github/appstore/Sample.mobileprovision '
runs:
  using: 'node12'
  main: 'dist/main.js'
  post: 'dist/clean.js'
